<?php

namespace YiiFileRepository\models;


use yii\base\InvalidConfigException;
use YiiHelper\abstracts\Model;
use Zf\Helper\Util;

/**
 * This is the model class for table "program_file_repository".
 *
 * @property int $id 自增ID
 * @property string $key 分类标识
 * @property string $unique_key 文件标识
 * @property string $label 显示名称
 * @property string $url url地址标志
 * @property int $sort_order 排序
 * @property string $description 描述
 * @property string $created_at 创建时间
 * @property string $updated_at 更新时间
 */
class FileRepository extends Model
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'program_file_repository';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['key'], 'required'],
            [['sort_order'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['key', 'unique_key', 'label'], 'string', 'max' => 100],
            [['url'], 'string', 'max' => 200],
            [['description'], 'string', 'max' => 255],
            [['key', 'label'], 'unique', 'targetAttribute' => ['key', 'label']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'          => '自增ID',
            'key'         => '分类标识',
            'unique_key'  => '文件标识',
            'label'       => '显示名称',
            'url'         => 'url地址标志',
            'sort_order'  => '排序',
            'description' => '描述',
            'created_at'  => '创建时间',
            'updated_at'  => '更新时间',
        ];
    }

    private $_oldUrl;

    /**
     * 入库前类型选项支持判断
     *
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if (empty($this->unique_key)) {
            $this->unique_key = Util::uniqid(); // 界面未传递标志key时，自动创建
        }
        $this->_oldUrl = $this->getOldAttribute('url');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * 入库后对文件处理
     *
     * @param bool $insert
     * @param array $changedAttributes
     * @throws InvalidConfigException
     */
    public function afterSave($insert, $changedAttributes)
    {
        replace_upload_file($this->url, $this->_oldUrl); // 持久化新文件，将老文件删除
        parent::afterSave($insert, $changedAttributes);
    }

    /**
     * 数据删除后文件处理
     *
     * @throws InvalidConfigException
     */
    public function afterDelete()
    {
        delete_upload_file($this->url); // 删除老图片
        parent::afterDelete();
    }
}
